### ISSUE TITLE
Failed to parse key in grouping when config value is left as default

### ISSUE THREAD

**Issue by dmcpriv** [CESNET/libyang#132]
When a key is defined in a group and included in a list via a "uses" statement, if the config value for the list is "false", and the config value for the leaf in the grouping is unspecified, the parsing fails since it thinks the config value for the leaf is "true".  

Shouldn't the config value for the leaf in the grouping be evaluated against the node it is "used" from?

The error returned is below.

libyang[0]: The "config" value of the "number" key differs from its list config value.

**Comment by rkrejci** [comment]
Can you provide an example module?

**Comment by dmcpriv** [comment]
I will try and construct a basic one with the same problem.

**Comment by dmcpriv** [comment]
```yang
<module name="ddd" xmlns="urn:ietf:params:xml:ns:yang:yin:1" xmlns:d="ddd">
  <namespace uri="ddd"/>
  <prefix value="ddd"/>
  <import module="r"> <prefix value="r"/> </import>
  <organization> <text>d</text> </organization>
  <contact> <text>d</text> </contact>
  <description> <text>d</text> </description>
  <revision date="2001-01-01"> <description> <text>1</text> </description> </revision>
  <grouping name="b">
    <list name="d">
      <key value="a"/>
      <leaf name="a">
        <type name="string"/>
      </leaf>  
      <config value="false"/>
    </list>
  </grouping>
  <container name="c">
    <uses name="b"/>
  </container>
</module>

```

gives me

libyang[2]: Reading module "ddd".
libyang[0]: The "config" value of the "a" key differs from its list config value. (path: /ddd:b/d)
libyang[0]: Module "ddd" parsing failed.

**Comment by dmcpriv** [comment]
this is in the devel branch, by the way...

**Comment by michalvasko** [comment]
Hi,
it should be fixed now.

Regards,
Michal

**Comment by davemiedema** [comment]
Thanks.  Can you let me know what commit fixes this in case I wanted a targetted patch for it?

**Comment by dmcpriv** [comment]
Thanks. Can you let me know what commit fixes this in case I wanted a targetted patch for it?

**Comment by rkrejci** [comment]
The commit is referenced above.

**Comment by dmcpriv** [comment]
I am still seeing similar problems in the latest devel branch.

**Comment by rkrejci** [comment]
can you be more specific? I just tried to load the module `ddd` given above with the current devel yanglint and everything seems ok.

**Comment by dmcpriv** [comment]
Sorry, of course.  I will try and find a simple example that has this problem.  It looks like the config attributes of the list is not applied to the elements pulled in via the uses.

**Comment by dmcpriv** [comment]
Here is a more complex model

```xml

<module name="test" xmlns="urn:ietf:params:xml:ns:yang:yin:1">
  <namespace uri="http://test"/>
  <prefix value="test"/>
  <organization>
    <text>Test</text>
  </organization>
  <contact>
    <text>Test</text>
  </contact>
  <description>
    <text>Test</text>
  </description>
  <revision date="2001-01-01">
    <description>
      <text>Test</text>
    </description>
  </revision>
  <grouping name="a">
    <leaf name="b">
      <type name="string"/>
    </leaf>
    <leaf name="c">
      <type name="string"/>
    </leaf>
  </grouping>
  <grouping name="d">
    <list name="d">
      <key value="f"/>
      <uses name="e"/>
    </list>
  </grouping>
  <grouping name="e">
    <leaf name="f">
      <type name="string"/>
    </leaf>
    <list name="g">
      <key value="b"/>
      <config value="false"/>
      <uses name="a"/>
    </list>
  </grouping>
  <uses name="h"/>
  <grouping name="h">
    <container name="i">
      <uses name="d"/>
    </container>
  </grouping>
</module>

```


pyang can parse it okay

```
> pyang -f tree test.yin
module: test
    +--rw i
       +--rw d* [f]
          +--rw f    string
          +--ro g* [b]
             +--ro b    string
             +--ro c?   string
```

But when I load it via libyang, I get the following:

```
libyang[0]: The "config" value of the "b" key differs from its list config value. (path: /test:e/g)
```

'b' should be config="false" by virtue of the "g" being config false.

Not sure if all the complexity is needed to reproduce this error, but included it all just in case.

**Comment by rkrejci** [comment]
should works with the current devel
