### ISSUE TITLE
About the order of nodes in rpc/action output/input

### ISSUE THREAD

**Issue by fanchanghu** [CESNET/libyang#608]
Hi,
It seems libyang requires all nodes in rpc/action output/input are in same order as defined in schema, this may be right for XML encoding, but may not be right for JSON encoding, the RFC 7951 has some descriptions about the order:
[section-5.4](https://tools.ietf.org/html/rfc7951#section-5.4):
```
   Unlike the XML encoding, where list keys are required to precede any
   other siblings within a list entry and appear in the order specified
   by the data model, the order of members in a JSON-encoded list entry
   is arbitrary because JSON objects are fundamentally unordered
   collections of members.
```
[section-7](https://tools.ietf.org/html/rfc7951#section-7):
```
   o  The order of JSON object members is never relied upon.
```
So, I think the order for output/input data tree could be arbitrary if it is JSON-encoded.

**Comment by michalvasko** [comment]
Hi,
the order should no longer be required and your example program should work now but let me just note that, strictly speaking, there is no standardized way of encoding RPCs/actions/rpc-replies into JSON (point me to some text if you know about one).

Regards,
Michal

**Comment by fanchanghu** [comment]
Hi,
Yes, you are right, there is no explicit specification about how to encode rpc/action as JSON, 
but the RFC 7951 says its encoding rules are identical for all types of data trees, 
we could naturally assume that there is no order restriction for rpc/action. :)
```
   ...
   The encoding rules are identical for all types of data trees, i.e.,
   configuration data, state data, parameters of RPC operations,
   actions, and notifications.
```

**Comment by fanchanghu** [comment]
And, maybe a problem for your change: if I print the data tree which is loaded from a JSON text as a XML text, the output should be sorted. (but it is not now)
```
lyd_print_file(stdout, dt2, LYD_XML, LYD_OPT_RPCREPLY);
```

**Comment by fanchanghu** [comment]
Hi,
It seems it still not work for action case, can you check following code, thanks.
```
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>

#include "libyang/libyang.h"

static const char *yang =
        R"(
module ListLeaf {
    namespace "http://example.net/zte/list/leaf";
    prefix ListLeaf;
    yang-version "1.1";

    container ListLeaf{
       leaf id{type uint32;}
    action setdata{
        input{
            container interfaces {
                list ifEntry {
                    key ifIndex;
                    leaf ifIndex {
                        type uint32;
                    }
                    leaf ifDescr {
                        type string;
                    }
                    leaf ifMtu {
                        type int32;                     
                    }
                }
            }
        }
        output{
            container interfaces {
                list ifEntry {
                    key ifDescr;
                    leaf ifDescr {
                        type string;
                    }
                    leaf ifMtu {
                        type int32;                     
                    }
                    leaf ifIndex {
                        type uint32;
                    }
                }
            }
        }
        
    }
 }
}
)";

const char *in = R"(
<ListLeaf xmlns="http://example.net/zte/list/leaf">
    <setdata>
    <interfaces>    
        <ifEntry>
            <ifIndex>2</ifIndex>
            <ifDescr>this is one</ifDescr>
            <ifMtu>2</ifMtu>        
        </ifEntry>
    </interfaces>
    </setdata>
</ListLeaf>
)";
const char *out = R"({"interfaces":{"ifEntry":[{"ifDescr":"thisisone","ifIndex":2,"ifMtu":2}]}})";

int main(void)
{
    int rc;
    const struct lys_module *mod;
    struct ly_ctx *ctx;
    struct lyd_node *dt, *dt2;

    ctx = ly_ctx_new(NULL, 0);
    assert(ctx);

    mod = lys_parse_mem(ctx, yang, LYS_IN_YANG);
    assert(mod);

    dt = lyd_parse_mem(ctx, in, LYD_XML, LYD_OPT_RPC, NULL);
    assert(dt);

    dt2 = lyd_parse_mem(ctx, out, LYD_JSON, LYD_OPT_RPCREPLY, dt, NULL);
    assert(dt2);

    lyd_print_file(stdout, dt2, LYD_XML, LYD_OPT_RPCREPLY);
    printf("\n");

    lyd_free(dt);
    lyd_free(dt2);

    ly_ctx_destroy(ctx, NULL);

    return 0;
}
```
the output is 
```
<ListLeaf xmlns="http://example.net/zte/list/leaf"><setdata><interfaces><ifEntry><ifDescr>thisisone</ifDescr><ifIndex>2</ifIndex><ifMtu>2</ifMtu></ifEntry></interfaces></setdata></ListLeaf>
```
it is not same with the schema (`ifIndex` and `ifMtu`).
